name = "ASK"
main = "src/worker.js"
compatibility_date = "2026-08-02"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

# wrangler kv namespace create ask_kv 실행 후 나오는 id를 아래에 넣어주세요.
[[kv_namespaces]]
binding = "ask_kv"
id = "717e2896f473415797b7ac2f08f648ce"

[observability]
enabled = true
